services:
  api:
    volumes:
      - ../proxy:/usr/src/app/proxy
    entrypoint: ["sh", "-c", "npm run dev $NODE_OPTIONS"]
    build:
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTP_PROXY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NODE_OPTIONS=${NODE_OPTIONS}

